language: cpp
before_install:
  #  - sudo apt-get update -qq
  - cd .. && mkdir -p src/UserCode && mv $OLDPWD src/UserCode/ICHiggsTauTau
  - export CMSSW_BASE=$PWD
  - cd src/UserCode/ICHiggsTauTau
install:
  #  - sudo apt-get install -qq doxygen
  - wget http://ftp.de.debian.org/debian/pool/main/d/doxygen/doxygen_1.8.8-5_amd64.deb
  - sudo dpkg -i doxygen_1.8.8-5_amd64.deb
script:
  - ./docs/publish-doxygen.sh 
#after_success:
git:
    submodules: false
env:
  global:
    - secure: "Z2fJnto1HUMOHY6r2iKlXKLiWCueVQ5SV6wMu08rUwW4skYCG6cC8xx1nMVCUrjcjp4R35qk5ARZOf8Y/8HR96HNXeUhvOPiPw250ly/GS4Y9b8M2LJsadwJF08axZFOh8hCUuMbMwSBgbk86Lp3XuLyoad3V+UlwwxaoSbJsD4="
# whitelist
branches:
  only:
    - master
notifications:
  email:
    - andrew.gilbert@cern.ch
