language: cpp
before_install:
  #  - sudo apt-get update -qq
  - sudo apt-add-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - sudo apt-get install git
  - cd .. && mkdir -p src/UserCode && mv $OLDPWD src/UserCode/ICHiggsTauTau
  - export CMSSW_BASE=$PWD
  - cd src/UserCode/ICHiggsTauTau
install:
  #  - sudo apt-get install -qq doxygen
  - export DOX=doxygen-1.8.8
  - wget -O - http://ftp.stack.nl/pub/users/dimitri/${DOX}.linux.bin.tar.gz |  tar xz -C ${TMPDIR-/tmp} ${DOX}/bin/doxygen
  - sudo install -m 755 ${TMPDIR-/tmp}/${DOX}/bin/doxygen /usr/local/bin/doxygen
script:
  - ./docs/publish-doxygen.sh 
#after_success:
git:
    submodules: false
env:
  global:
    - secure: "RcuotvBQtnzoEsaN9pfcQ9w+F5Dc8hkcPmaH1PR5uwPHnVd74ZkCSsafPdBG2T7JlIvQpKNhYrHYVEdQ49csr5dBfNH7EtewZ4tyCFCRvb6fr7IGn5nO3g1yp0HCnDqZ9fhuuEjveVMCe1QBK9swc0k4bciUtRZsBN8lEN/TVIQ=" 
# whitelist
branches:
  only:
    - master
notifications:
  email:
    - andrew.gilbert@cern.ch
